// SPDX-License-Identifier: MPL-2.0

// Real sockets on loopback, not mocked transport. Bound ports are ephemeral.
DispatchQueue.global().asyncAfter(deadline: .now() + 10) {
    fatalError("Network regression test timed out waiting for a datagram")
}
check(IPNetwork.normalized("[2001:0db8:0:0::1]") == "2001:db8::1", "IPv6 normalization removes brackets and alternate spelling")
check(IPNetwork.normalized("::ffff:192.168.1.2") == "192.168.1.2", "mapped IPv4 retains legacy source strings")
let scope = if_nametoindex("lo0")
check(scope > 0 && IPNetwork.normalized("[fe80::1%25lo0]") == "fe80::1%\(scope)", "IPv6 scope is normalized using the receiving device's interface")
// Synthetic CGNAT-range fixture; no connection to a real Tailscale peer is made.
let exampleTailscaleAddress = "100.64.0.1"
check(ClientNetworkAddressPolicy.localWiFiHost(savedHost: "192.168.1.2", discoveredHost: nil, deviceHost: "192.168.1.3", deviceNetmask: "255.255.255.0") == "192.168.1.2", "explicit Wi-Fi attempt uses a saved same-subnet address")
check(ClientNetworkAddressPolicy.localWiFiHost(savedHost: "192.168.2.2", discoveredHost: nil, deviceHost: "192.168.1.3", deviceNetmask: "255.255.255.0") == nil, "stale LAN address waits for discovery instead of using Tailscale")
check(ClientNetworkAddressPolicy.localWiFiHost(savedHost: exampleTailscaleAddress, discoveredHost: nil, deviceHost: "192.168.1.3", deviceNetmask: "255.255.255.0") == nil, "Wi-Fi-only attempt never selects a saved VPN address")
check(ClientNetworkAddressPolicy.localWiFiHost(savedHost: "192.168.2.2", discoveredHost: "192.168.1.8", deviceHost: "192.168.1.3", deviceNetmask: "255.255.255.0") == "192.168.1.8", "fresh paired Bonjour result replaces a stale saved address")
check(ClientNetworkAddressPolicy.localWiFiHost(savedHost: "", discoveredHost: "fd00:2::8", deviceHost: "192.168.1.3", deviceNetmask: "255.255.255.0") == "fd00:2::8", "fresh IPv6 Bonjour route does not require an IPv4 subnet match")
for invalidLocalHost in [exampleTailscaleAddress, "fd7a:115c:a1e0::8", "127.0.0.1", "::", "8.8.8.8"] {
    check(ClientNetworkAddressPolicy.localWiFiHost(savedHost: "", discoveredHost: invalidLocalHost, deviceHost: "192.168.1.3", deviceNetmask: "255.255.255.0") == nil, "Wi-Fi discovery rejects VPN, loopback, unspecified and public endpoints: \(invalidLocalHost)")
}
check(IPNetwork.isTailscale(exampleTailscaleAddress) && IPNetwork.isTailscale("fd7a:115c:a1e0::1"), "both Tailscale address families are recognized")
check(ClientNetworkAddressPolicy.isTailscaleInterface(name: "utun4", address: exampleTailscaleAddress), "Tailscale address on a VPN tunnel interface is an active Tailscale route")
check(ClientNetworkAddressPolicy.isTailscaleInterface(name: "utun3", address: "fd7a:115c:a1e0::1"), "IPv6 Tailscale address on a tunnel interface is an active Tailscale route")
check(!ClientNetworkAddressPolicy.isTailscaleInterface(name: "pdp_ip0", address: "100.80.1.2"), "carrier CGNAT cellular address is not treated as an active Tailscale route")
check(!ClientNetworkAddressPolicy.isTailscaleInterface(name: "en0", address: exampleTailscaleAddress), "Wi-Fi interface in the CGNAT range is not treated as Tailscale")
check(!ClientNetworkAddressPolicy.isTailscaleInterface(name: "utun4", address: "10.8.0.2"), "other VPN tunnels are not treated as Tailscale")
check(IPNetwork.sameSubnet("fd00:1::a", "fd00:1::b", netmask: "ffff:ffff:ffff:ffff::"), "IPv6 LAN subnet comparison works")
check(!IPNetwork.sameSubnet("fd00:1::a", "fd00:2::b", netmask: "ffff:ffff:ffff:ffff::"), "different IPv6 subnets do not match")
check(!IPNetwork.sameSubnet("fe80::1%1", "fe80::2%2", netmask: "ffff:ffff:ffff:ffff::"), "link-local scopes on different interfaces do not match")
check(IPNetwork.destination(host: "localhost", port: 5555) != nil, "hostnames resolve through the system resolver")
check(IPNetwork.normalized("fe80::1%25") == "fe80::1%25", "raw numeric scope 25 is not mistaken for URL escaping")
check(IPNetwork.pairingLocalHost(advertised: "fe80::1%99") == nil, "pairing links never import a remote interface scope")
check(IPNetwork.pairingLocalHost(advertised: "fe80::1%99", connectedHost: "fe80::1%2") == "fe80::1%2", "authenticated pairing retains the successful receiver-local Bonjour scope")
check(IPNetwork.pairingLocalHost(advertised: "192.168.1.1", connectedHost: "fd00::1") == "fd00::1", "pairing retains the authenticated IPv6 route instead of an unreachable advertised IPv4 address")
check(IPNetwork.pairingLocalHost(advertised: "192.168.1.1", connectedHost: exampleTailscaleAddress) == "192.168.1.1", "remote Tailscale pairing does not overwrite the Mac's LAN address")
check(IPNetwork.pairingTailscaleCandidates(codeHost: nil, advertisedHost: "fd7a:115c:a1e0::2") == ["fd7a:115c:a1e0::2"], "IPv6-only Tailscale QR endpoint is attempted even without a code IPv4 locator")
check(IPNetwork.pairingTailscaleCandidates(codeHost: exampleTailscaleAddress, advertisedHost: "fd7a:115c:a1e0::2") == [exampleTailscaleAddress, "fd7a:115c:a1e0::2"], "compact-code route and advertised IPv6 route coexist")
check(IPNetwork.pairingTailscaleCandidates(codeHost: nil, advertisedHost: "2001:db8::2").isEmpty, "arbitrary public IPv6 metadata is not treated as a Tailscale pairing endpoint")
check(IPNetwork.pairingTailscaleHost(advertised: exampleTailscaleAddress, connectedHost: "fd7a:115c:a1e0::2") == "fd7a:115c:a1e0::2", "authenticated IPv6 Tailscale route survives the approved pairing response")
check(ClientNetworkAddressPolicy.shouldTryLocalRoute(localHost: "fd00:1::a", deviceHost: "fd00:1::b", deviceNetmask: "ffff:ffff:ffff:ffff::"), "iOS routing selects same-subnet IPv6")
check(NetworkAddressPolicy.isOnSameSubnet(peerAddress: "192.168.1.2", interfaceAddress: "192.168.1.3", netmask: "255.255.255.0"), "macOS routing preserves IPv4 subnet selection")
check(ClientNetworkAddressPolicy.shouldAcceptAuthenticatedStreamPeer(configuredHost: "192.168.1.2", sourceHost: "fd7a:115c:a1e0::2"), "authenticated stream can move between LAN and IPv6 Tailscale")
check(!ClientNetworkAddressPolicy.shouldAcceptDetectedPeer(configuredHost: "fd00::1", detectedHost: "fd00::2"), "unverified IPv6 source is not treated as the configured host")
check(!NetworkAddressPolicy.shouldAcceptAuthenticatedStreamPeer(configuredHost: "fd00::1", sourceHost: "::"), "unspecified IPv6 source is rejected")
let remoteCode = PairingInvitationCode.generate(tailscaleAddress: exampleTailscaleAddress)
let decodedRemoteCode = try PairingInvitationCode.decode(remoteCode)
check(PairingInvitationCode.normalized(remoteCode).count == 12 && decodedRemoteCode.tailscaleAddress == exampleTailscaleAddress, "12-character Computer Code retains its existing Tailscale locator")
let localCode = PairingInvitationCode.generate(tailscaleAddress: nil)
let decodedLocalCode = try PairingInvitationCode.decode(localCode)
check(decodedLocalCode.tailscaleAddress == nil, "local-only Computer Code remains valid for Bonjour pairing")

let port = unusedUDPPort()
let receiver = try UDPReceiver(port: port)
let ipv4 = try UDPSender(host: "127.0.0.1", port: port)
let ipv6 = try UDPSender(host: "::1", port: port)
let message = Data("PocketCtrl dual-stack test".utf8)
try ipv4.send(message)
let v4 = receiver.receiveWithSource()
check(v4?.data == message && v4?.sourceHost == "127.0.0.1", "macOS dual-stack receiver accepts existing IPv4 sender traffic")
try ipv6.send(message)
let v6 = receiver.receiveWithSource()
check(v6?.data == message && v6?.sourceHost == "::1", "macOS sender and receiver exchange native IPv6 datagrams")
let fanout = try UDPMultiPeerSender()
try fanout.send(message, toHost: "127.0.0.1", port: port)
check(receiver.receiveWithSource()?.sourceHost == "127.0.0.1", "per-viewer fanout retains IPv4 replies")
try fanout.send(message, toHost: "::1", port: port)
check(receiver.receiveWithSource()?.sourceHost == "::1", "same fanout sender supports IPv6 replies")

let mobilePort = unusedUDPPort()
let mobile = try ClientUDPReceiver(port: mobilePort)
try fanout.send(message, toHost: "127.0.0.1", port: mobilePort)
let mobileV4 = mobile.receive()
check(mobileV4?.data == message && mobileV4?.senderAddress == "127.0.0.1", "iOS receiver source code receives IPv4 without changing peer identity")
try fanout.send(message, toHost: "::1", port: mobilePort)
let mobileV6 = mobile.receive()
check(mobileV6?.data == message && mobileV6?.senderAddress == "::1", "iOS receiver source code receives IPv6")
mobile.stop()
receiver.stop()
fanout.stop()
ipv4.stop()
ipv6.stop()
